name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Run Docker Container
        uses: addnab/docker-run-action@v3
        with:
          image: osrf/ros:melodic-desktop-full
          options: --rm --privileged
          run: |
            # Update package lists and initialize rosdep
            apt-get update -qq
            apt-get install -qq -y python-rosdep python-catkin-tools
            rosdep init
            rosdep update

            # Source ROS environment
            source /opt/ros/melodic/setup.bash

            # Build the project (adjust to your build system)
            mkdir -p ~/catkin_ws/src
            cp -r . ~/catkin_ws/src/
            cd ~/catkin_ws
            catkin_make

            # Run tests
            catkin_make run_tests
            catkin_test_results
