name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - name: Install ROS Melodic
        run: |
          apt-get update -qq && \
          apt-get install -qq -y curl gpg-agent && \
          sh -c 'echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros-latest.list' && \
          curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - && \
          apt-get update -qq && \
          apt-get install -qq -y ros-melodic-desktop-full && \
          echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc && \
          apt-get install -qq -y python-rosdep python-catkin-tools && \
          rosdep init && \
          rosdep update

      - name: Install gTest
        run: |
          apt-get install -y libgtest-dev cmake
          mkdir -p build && cd build
          cmake /usr/src/googletest
          make
          cp lib/libgtest* /usr/lib/

      - name: Setup ROS Environment
        run: |
          echo "source /opt/ros/melodic/setup.bash" >> $GITHUB_ENV

      - name: Build Project
        run: |
          source /opt/ros/melodic/setup.bash
          cmake --preset default
          cmake --build --preset default --config Debug --target install
