name: ROS Melodic CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up ROS
      run: |
        sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
        sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key F42ED6FBAB17C654
        sudo apt update
        sudo apt install -y ros-melodic-desktop-full
        echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc
        source /opt/ros/melodic/setup.bash
        sudo apt install -y python-rosdep python-rosinstall python-rosinstall-generator python-wstool build-essential
        sudo rosdep init
        rosdep update

    - name: Setup ROS workspace
      run: |
        mkdir -p ~/ros_ws/src
        cd ~/ros_ws/src
        ln -s $GITHUB_WORKSPACE .
        cd ~/ros_ws
        rosdep install --from-paths src --ignore-src -r -y
        catkin_make

    - name: Run tests
      run: |
        source ~/ros_ws/devel/setup.bash
        catkin_make run_tests
        catkin_test_results
