name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install gTest
        run: |
          sudo apt-get install -y libgtest-dev cmake
          mkdir -p build && cd build
          cmake /usr/src/googletest
          make
          sudo cp lib/libgtest* /usr/lib/

      - name: Build Project
        run: |
          cmake --preset default
          cmake --build --preset default --config Debug --target install
